steps:
- checkout: none # skip checking out the default repository resource
- task: DownloadBuildArtifacts@0
  displayName: Download Build Artifacts
  inputs:
    artifactName: deployables
    downloadPath: $(System.DefaultWorkingDirectory)
- task: Bash@3
  displayName: Consume NB.GV from .NET Core build
  inputs:
    failOnStderr: true
    targetType: inline
    script: >
      if hash gfind 2>/dev/null; then
        # OSX
        PkgFileName=$(gfind deployables/*nupkg -printf "%f\n")
      else
        # Linux
        PkgFileName=$(find deployables/*nupkg -printf "%f\n")
      fi

      NBGV_NuGetPackageVersion=$([[ $PkgFileName =~ Nerdbank.GitVersioning\.(.*)\.nupkg ]] && echo "${BASH_REMATCH[1]}")

      echo "<configuration><packageSources><clear /><add key='local' value='deployables' /></packageSources></configuration>" > nuget.config &&
      dotnet new classlib -o lib &&
      cd lib &&
      echo '{"version":"42.42"}' > version.json &&
      git init &&
      git add lib.csproj version.json Class1.cs &&
      dotnet add package nerdbank.gitversioning -v $NBGV_NuGetPackageVersion &&
      git commit -m "Initial commit" &&
      dotnet pack -c debug &&
      if [ ! -f "bin/debug/lib.42.42.1.nupkg" ]; then exit 1; fi
